"""Σταθερές Email Marketing module."""

CAMPAIGN_STATUS_DRAFT = "Draft"
CAMPAIGN_STATUS_SCHEDULED = "Scheduled"
CAMPAIGN_STATUS_SENT = "Sent"
CAMPAIGN_STATUSES = (CAMPAIGN_STATUS_DRAFT, CAMPAIGN_STATUS_SCHEDULED, CAMPAIGN_STATUS_SENT)

AUDIENCE_ALL = "all"
AUDIENCE_ACTIVE_30D = "active_30d"
AUDIENCE_INACTIVE_6M = "inactive_6m"
AUDIENCE_RECENT_BUYERS = "recent_buyers"
AUDIENCE_SUBSCRIBED_ONLY = "subscribed_only"
AUDIENCE_NEVER_BOUGHT = "never_bought"
AUDIENCE_WITH_PURCHASE = "with_purchase"
AUDIENCE_NEW_30D = "new_30d"
AUDIENCE_FILTERS = (
    AUDIENCE_ALL,
    AUDIENCE_SUBSCRIBED_ONLY,
    AUDIENCE_ACTIVE_30D,
    AUDIENCE_RECENT_BUYERS,
    AUDIENCE_NEW_30D,
    AUDIENCE_WITH_PURCHASE,
    AUDIENCE_NEVER_BOUGHT,
    AUDIENCE_INACTIVE_6M,
)

DEFAULT_BATCH_SIZE = 50

STANDARD_TEMPLATE_VARIABLES = (
    "client_name",
    "client_email",
    "product_list",
    "company_name",
)
