/**
 * Θέματα αρχικής = ΔΙΑΤΑΞΗ (header × hero × trips × cards × footer).
 * Τα χρώματα είναι προτεινόμενα και εφαρμόζονται χωριστά (Γενικά → Brand colors),
 * εκτός αν ζητηθεί ρητά includeColors στο themeToAppearancePatch.
 */

export const THEME_CATEGORIES = [
  { id: 'all', label: 'Όλα', icon: 'apps' },
  { id: 'premium', label: 'Premium', icon: 'diamond' },
  { id: 'minimal', label: 'Minimal', icon: 'crop_free' },
  { id: 'bold', label: 'Έντονα', icon: 'bolt' },
  { id: 'corporate', label: 'Corporate', icon: 'business_center' },
  { id: 'seasonal', label: 'Εποχιακά', icon: 'sunny' },
];

/**
 * 18 θέματα με μέγιστη δομική διαφορά μεταξύ τους.
 * Κάθε θέμα χρησιμοποιεί μοναδικό συνδυασμό templates ώστε να «αφήνει ιστορία».
 */
export const HOMEPAGE_THEMES = [
  {
    id: 'aegean_classic',
    name: 'Aegean Classic',
    nameEl: 'Αιγαίο Classic',
    description: 'Fullscreen hero, 3στήλο premium grid — το κλασικό ταξιδιωτικό look.',
    mood: 'Αιγαίο · αξιοπιστία',
    badge: 'Default',
    category: 'premium',
    tags: ['Fullscreen', '3 στήλες', 'Premium'],
    layoutLabel: 'Fullscreen · Grid 3',
    palette: { primary: '#0ea5e9', secondary: '#1e3a5f', hero: '#0f172a', surface: '#f8fafc' },
    header_template: 'glass_dark',
    hero_template: 'fullscreen_overlay',
    trips_layout_template: 'grid_three',
    trip_card_template: 'premium',
    footer_template: 'classic_columns',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'Ανακαλύψτε',
    trips_section_title: 'Εκδρομές στην Ελλάδα',
    trips_section_subtitle: 'Ημερήσιες και πολυήμερες διαδρομές με premium στόλο — κράτηση θέσης online.',
  },
  {
    id: 'cycladic_white',
    name: 'Cycladic White',
    nameEl: 'Κυκλαδίτικο Λευκό',
    description: 'Minimal header, συμπαγής λίστα, καθαρή κεντρική σύνθεση — boutique νησί.',
    mood: 'Ήρεμο · λευκό',
    badge: 'Boutique',
    category: 'minimal',
    tags: ['Minimal', 'Λίστα', 'Ήσυχο'],
    layoutLabel: 'Minimal · Λίστα',
    palette: { primary: '#64748b', secondary: '#334155', hero: '#1e293b', surface: '#ffffff' },
    header_template: 'transparent_minimal',
    hero_template: 'centered_compact',
    trips_layout_template: 'compact_list',
    trip_card_template: 'minimal_clean',
    footer_template: 'minimal_center',
    show_fleet_section: false,
    show_why_us_section: true,
    trips_section_eyebrow: 'Επιλογές',
    trips_section_title: 'Επιλεγμένες διαδρομές',
    trips_section_subtitle: 'Λίγες, προσεγμένες εκδρομές — χωρίς θόρυβο, μόνο ουσία.',
  },
  {
    id: 'olympia_luxe',
    name: 'Olympia Luxe',
    nameEl: 'Olympia Luxe',
    description: 'Elegant border, card-inset hero, masonry magazine — VIP στόλος.',
    mood: 'VIP · χλιδή',
    badge: 'VIP',
    category: 'premium',
    tags: ['Inset hero', 'Masonry', 'Magazine'],
    layoutLabel: 'Inset · Masonry',
    palette: { primary: '#c9a227', secondary: '#0f172a', hero: '#020617', surface: '#f1f5f9' },
    header_template: 'bordered_elegant',
    hero_template: 'card_inset',
    trips_layout_template: 'masonry_two',
    trip_card_template: 'magazine',
    footer_template: 'dark_band',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'Private & VIP',
    trips_section_title: 'Luxury διαδρομές',
    trips_section_subtitle: 'Επιλεγμένα δρομολόγια με premium coach και προσωπική εξυπηρέτηση.',
  },
  {
    id: 'santorini_split',
    name: 'Santorini Split',
    nameEl: 'Σαντορίνη Split',
    description: 'Split hero 50/50, εναλλασσόμενες story σειρές — cinematic storytelling.',
    mood: 'Ηλιοβασίλεμα · story',
    badge: 'Story',
    category: 'seasonal',
    tags: ['Split', 'Story rows', 'Overlay'],
    layoutLabel: 'Split · Story rows',
    palette: { primary: '#f59e0b', secondary: '#0f766e', hero: '#7c2d12', surface: '#fffbeb' },
    header_template: 'solid_light',
    hero_template: 'split_left',
    trips_layout_template: 'alternating_rows',
    trip_card_template: 'image_overlay',
    footer_template: 'split_contact',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'Ήλιος & θάλασσα',
    trips_section_title: 'Μεσογειακές αποδράσεις',
    trips_section_subtitle: 'Επιλεγμένες διαδρομές με άπλετο φως — ιδανικές για καλοκαιρινές κρατήσεις.',
  },
  {
    id: 'metro_ticket',
    name: 'Metro Ticket',
    nameEl: 'Metro Ticket',
    description: 'Search στο hero, πυκνή λίστα, κάρτες-εισιτήρια — γρήγορες κρατήσεις.',
    mood: 'Ταχύτητα · πόλη',
    badge: 'Express',
    category: 'bold',
    tags: ['Search', 'Ticket cards', 'Dense'],
    layoutLabel: 'Search · Tickets',
    palette: { primary: '#dc2626', secondary: '#111827', hero: '#450a0a', surface: '#fef2f2' },
    header_template: 'gradient_bar',
    hero_template: 'bottom_search',
    trips_layout_template: 'compact_list',
    trip_card_template: 'ticket_stub',
    footer_template: 'compact_inline',
    show_fleet_section: true,
    show_why_us_section: false,
    trips_section_eyebrow: 'Departing soon',
    trips_section_title: 'Express αναχωρήσεις',
    trips_section_subtitle: 'Συμπαγής λίστα για γρήγορη επιλογή και άμεση κράτηση.',
  },
  {
    id: 'island_bento',
    name: 'Island Bento',
    nameEl: 'Νησιωτικό Bento',
    description: 'Gallery προορισμών 3+2 με poster κάρτες — πλήρης φωτογραφία.',
    mood: 'Gallery · νησιά',
    badge: 'Gallery',
    category: 'premium',
    tags: ['Bento 3+2', 'Posters', 'Gallery'],
    layoutLabel: 'Bento · Posters',
    palette: { primary: '#0f172a', secondary: '#64748b', hero: '#020617', surface: '#f1f5f9' },
    header_template: 'solid_light',
    hero_template: 'centered_compact',
    trips_layout_template: 'destination_bento',
    trip_card_template: 'destination_poster',
    footer_template: 'classic_columns',
    show_fleet_section: true,
    show_why_us_section: false,
    trips_section_eyebrow: 'Προορισμοί',
    trips_section_title: 'Εκδρομές με λεωφορείο',
    trips_section_subtitle: 'Διάλεξε προορισμό — τιμή θέσης και ημερομηνία αναχώρησης.',
  },
  {
    id: 'editorial_voyage',
    name: 'Editorial Voyage',
    nameEl: 'Editorial Voyage',
    description: 'Περιοδικό look: editorial stack, μεγάλοι τίτλοι, storytelling.',
    mood: 'Περιοδικό · αφήγηση',
    badge: 'Editorial',
    category: 'premium',
    tags: ['Editorial stack', 'Magazine', 'Elegant'],
    layoutLabel: 'Editorial · Magazine',
    palette: { primary: '#18181b', secondary: '#71717a', hero: '#09090b', surface: '#fafafa' },
    header_template: 'bordered_elegant',
    hero_template: 'split_left',
    trips_layout_template: 'editorial_stack',
    trip_card_template: 'magazine',
    footer_template: 'classic_columns',
    show_fleet_section: false,
    show_why_us_section: true,
    trips_section_eyebrow: 'Features',
    trips_section_title: 'Ιστορίες ταξιδιού',
    trips_section_subtitle: 'Κάθε εκδρομή σαν editorial feature — χώρος να «αναπνεύσει» η αφήγηση.',
  },
  {
    id: 'glass_atlas',
    name: 'Glass Atlas',
    nameEl: 'Glass Atlas',
    description: 'Floating pill, mesh hero, glass cards σε masonry — ultra modern.',
    mood: 'Futuristic · soft',
    badge: 'Modern',
    category: 'minimal',
    tags: ['Floating', 'Mesh', 'Glass'],
    layoutLabel: 'Floating · Glass',
    palette: { primary: '#7c3aed', secondary: '#0891b2', hero: '#312e81', surface: '#f5f3ff' },
    header_template: 'floating_pill',
    hero_template: 'gradient_mesh',
    trips_layout_template: 'masonry_two',
    trip_card_template: 'glass_card',
    footer_template: 'minimal_center',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'Curated',
    trips_section_title: 'Σύγχρονες διαδρομές',
    trips_section_subtitle: 'Ελαφρύ UI, έντονα accents — ιδανικό για digital-first κοινό.',
  },
  {
    id: 'family_road',
    name: 'Family Road',
    nameEl: 'Οικογενειακό Road',
    description: 'Δύο μεγάλες κάρτες, οριζόντια info — καθαρό για οικογένειες.',
    mood: 'Οικογένεια · ασφάλεια',
    badge: 'Family',
    category: 'corporate',
    tags: ['2 μεγάλες', 'Horizontal', 'Contact'],
    layoutLabel: '2 μεγάλες · Horizontal',
    palette: { primary: '#16a34a', secondary: '#0369a1', hero: '#14532d', surface: '#f0fdf4' },
    header_template: 'solid_light',
    hero_template: 'fullscreen_overlay',
    trips_layout_template: 'grid_two_large',
    trip_card_template: 'compact_horizontal',
    footer_template: 'split_contact',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'Για όλους',
    trips_section_title: 'Οικογενειακές εκδρομές',
    trips_section_subtitle: 'Άνετες θέσεις, ξεκάθαρη πληροφόρηση — ιδανικό για οικογένειες.',
  },
  {
    id: 'europa_corridor',
    name: 'Europa Corridor',
    nameEl: 'Europa Corridor',
    description: 'Διεθνή δρομολόγια: editorial stack + abroad horizontal κάρτες.',
    mood: 'Διεθνές · express',
    badge: 'EU',
    category: 'corporate',
    tags: ['Abroad cards', 'Floating', 'Cross-border'],
    layoutLabel: 'Abroad · Editorial',
    palette: { primary: '#2563eb', secondary: '#1e40af', hero: '#1e3a8a', surface: '#eff6ff' },
    header_template: 'floating_pill',
    hero_template: 'fullscreen_overlay',
    trips_layout_template: 'grid_two_large',
    trip_card_template: 'premium',
    intl_trips_layout_template: 'editorial_stack',
    intl_trip_card_template: 'abroad_horizontal',
    footer_template: 'compact_inline',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'Cross-border',
    trips_section_title: 'Ευρωπαϊκά δρομολόγια',
    trips_section_subtitle: 'Αναχωρήσεις προς Ευρώπη με ξεκάθαρη τιμολόγηση και γρήγορη κράτηση.',
  },
  {
    id: 'midnight_charter',
    name: 'Midnight Charter',
    nameEl: 'Midnight Charter',
    description: 'Noir cinematic: σκούρο surface, luxe κάρτες, dark band footer.',
    mood: 'Νύχτα · luxe',
    badge: 'Noir',
    category: 'premium',
    tags: ['Dark', 'Luxe noir', 'Cinematic'],
    layoutLabel: 'Noir · Dark band',
    palette: { primary: '#a78bfa', secondary: '#fbbf24', hero: '#0c0a09', surface: '#1c1917' },
    header_template: 'glass_dark',
    hero_template: 'fullscreen_overlay',
    trips_layout_template: 'grid_two_large',
    trip_card_template: 'luxe_noir',
    footer_template: 'dark_band',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'After dark',
    trips_section_title: 'Night experiences',
    trips_section_subtitle: 'Σκούρο UI με χρυσές λεπτομέρειες — για premium νυχτερινές εμπειρίες.',
  },
  {
    id: 'spotlight_arena',
    name: 'Spotlight Arena',
    nameEl: 'Spotlight Arena',
    description: 'Featured + grid, spotlight κάρτες, search hero — μεγιστοποιεί μετατροπές.',
    mood: 'Conversion · ROI',
    badge: 'Convert',
    category: 'corporate',
    tags: ['Featured+', 'Spotlight', 'Search'],
    layoutLabel: 'Featured+ · Spotlight',
    palette: { primary: '#0284c7', secondary: '#0c4a6e', hero: '#082f49', surface: '#f0f9ff' },
    header_template: 'floating_pill',
    hero_template: 'bottom_search',
    trips_layout_template: 'featured_plus_grid',
    trip_card_template: 'spotlight',
    footer_template: 'newsletter_cta',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'Book now',
    trips_section_title: 'Διαθέσιμες εκδρομές',
    trips_section_subtitle: 'Καθαρή ιεραρχία και CTA σε κάθε κάρτα — σχεδιασμένο για μετατροπές.',
  },
  {
    id: 'scroll_coast',
    name: 'Scroll Coast',
    nameEl: 'Scroll Coast',
    description: 'Οριζόντιο swipe καρουζέλ, soft Apple κάρτες — mobile-first παραλία.',
    mood: 'Παραλία · swipe',
    badge: 'Mobile',
    category: 'seasonal',
    tags: ['Horizontal scroll', 'Soft', 'Mobile'],
    layoutLabel: 'Scroll · Soft cards',
    palette: { primary: '#f43f5e', secondary: '#0ea5e9', hero: '#9f1239', surface: '#fff1f2' },
    header_template: 'transparent_minimal',
    hero_template: 'gradient_mesh',
    trips_layout_template: 'horizontal_scroll',
    trip_card_template: 'soft_apple',
    footer_template: 'minimal_center',
    show_fleet_section: false,
    show_why_us_section: true,
    trips_section_eyebrow: 'Hot list',
    trips_section_title: 'Καλοκαιρινά hits',
    trips_section_subtitle: 'Οι πιο ζεστές διαδρομές της σεζόν — σύρετε και κλείστε θέση.',
  },
  {
    id: 'heritage_route',
    name: 'Heritage Route',
    nameEl: 'Διαδρομή Κληρονομιάς',
    description: 'Story rows + sharp bordered κάρτες — πολιτιστικές περιηγήσεις.',
    mood: 'Πολιτισμός · παράδοση',
    badge: 'Heritage',
    category: 'premium',
    tags: ['Story rows', 'Sharp', 'Classic'],
    layoutLabel: 'Story · Sharp cards',
    palette: { primary: '#c2410c', secondary: '#1e3a5f', hero: '#431407', surface: '#fff7ed' },
    header_template: 'bordered_elegant',
    hero_template: 'split_left',
    trips_layout_template: 'alternating_rows',
    trip_card_template: 'bordered_sharp',
    footer_template: 'classic_columns',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'Heritage',
    trips_section_title: 'Πολιτιστικές διαδρομές',
    trips_section_subtitle: 'Μνημεία, ιστορία και τοπική γεύση — αφήγηση σε κάθε στάση.',
  },
  {
    id: 'command_hub',
    name: 'Command Hub',
    nameEl: 'Command Hub',
    description: '4στήλο dense catalog + search — B2B / πλούσιος κατάλογος.',
    mood: 'Business · κατάλογος',
    badge: 'B2B',
    category: 'corporate',
    tags: ['4 στήλες', 'Search', 'Catalog'],
    layoutLabel: 'Grid 4 · Soft',
    palette: { primary: '#0f766e', secondary: '#334155', hero: '#0f172a', surface: '#f8fafc' },
    header_template: 'floating_pill',
    hero_template: 'bottom_search',
    trips_layout_template: 'grid_four',
    trip_card_template: 'soft_apple',
    footer_template: 'compact_inline',
    show_fleet_section: false,
    show_why_us_section: false,
    trips_section_eyebrow: 'Schedule',
    trips_section_title: 'Επαγγελματικά δρομολόγια',
    trips_section_subtitle: 'Γρήγορη επισκόπηση διαδρομών — ιδανικό για επαναλαμβανόμενες κρατήσεις.',
  },
  {
    id: 'harbor_market',
    name: 'Harbor Market',
    nameEl: 'Λιμάνι Market',
    description: 'Bento showcase + destination posters + newsletter — marketplace vibe.',
    mood: 'Αγορά · προορισμοί',
    badge: 'Market',
    category: 'bold',
    tags: ['Bento', 'Posters', 'Newsletter'],
    layoutLabel: 'Bento showcase · Posters',
    palette: { primary: '#ea580c', secondary: '#6d28d9', hero: '#431407', surface: '#fff7ed' },
    header_template: 'solid_light',
    hero_template: 'card_inset',
    trips_layout_template: 'bento_showcase',
    trip_card_template: 'destination_poster',
    footer_template: 'newsletter_cta',
    show_fleet_section: true,
    show_why_us_section: false,
    trips_section_eyebrow: 'Marketplace',
    trips_section_title: 'Προορισμοί σε βιτρίνα',
    trips_section_subtitle: 'Ασύμμετρο showcase — μία ηρωική κάρτα και δορυφόροι.',
  },
  {
    id: 'ampere_bold',
    name: 'Ampere Bold',
    nameEl: 'Ampere Bold',
    description: 'Gradient bar, mesh hero, οριζόντιο scroll με sharp κάρτες — νεανική ένταση.',
    mood: 'Ενέργεια · νεανικό',
    badge: 'Bold',
    category: 'bold',
    tags: ['Gradient', 'Scroll', 'Sharp'],
    layoutLabel: 'Mesh · Sharp scroll',
    palette: { primary: '#ea580c', secondary: '#6d28d9', hero: '#431407', surface: '#fff7ed' },
    header_template: 'gradient_bar',
    hero_template: 'gradient_mesh',
    trips_layout_template: 'horizontal_scroll',
    trip_card_template: 'bordered_sharp',
    footer_template: 'dark_band',
    show_fleet_section: true,
    show_why_us_section: false,
    trips_section_eyebrow: 'Next stop',
    trips_section_title: 'Περιπέτειες τώρα',
    trips_section_subtitle: 'Γρήγορες κρατήσεις, έντονες εμπειρίες — σύρετε για περισσότερα.',
  },
  {
    id: 'paper_atlas',
    name: 'Paper Atlas',
    nameEl: 'Paper Atlas',
    description: 'Ultra clean: transparent header, compact hero, soft 3στήλο — μηδέν θόρυβος.',
    mood: 'Zero noise · focus',
    badge: 'Clean',
    category: 'minimal',
    tags: ['Ultra clean', 'Soft Apple', 'Focus'],
    layoutLabel: 'Clean · Soft 3-col',
    palette: { primary: '#171717', secondary: '#525252', hero: '#0a0a0a', surface: '#ffffff' },
    header_template: 'transparent_minimal',
    hero_template: 'centered_compact',
    trips_layout_template: 'grid_three',
    trip_card_template: 'soft_apple',
    footer_template: 'minimal_center',
    show_fleet_section: false,
    show_why_us_section: false,
    trips_section_eyebrow: 'Trips',
    trips_section_title: 'Διαδρομές',
    trips_section_subtitle: 'Μόνο τίτλος, ημερομηνία και τιμή — χωρίς διακοσμητικό θόρυβο.',
  },
];

export const DEFAULT_HOMEPAGE_THEME_ID = 'aegean_classic';

export function getHomepageThemeById(id) {
  return HOMEPAGE_THEMES.find((t) => t.id === id) || HOMEPAGE_THEMES[0];
}

/**
 * Μετατρέπει θέμα σε patch για site appearance API.
 * @param {{ includeColors?: boolean }} options — by default ΜΟΝΟ διάταξη (όχι χρώματα).
 */
export function themeToAppearancePatch(theme, { includeColors = false } = {}) {
  const t = theme || getHomepageThemeById(DEFAULT_HOMEPAGE_THEME_ID);
  const patch = {
    homepage_theme_id: t.id,
    header_template: t.header_template,
    hero_template: t.hero_template,
    trips_layout_template: t.trips_layout_template,
    trip_card_template: t.trip_card_template,
    footer_template: t.footer_template,
  };
  if (t.intl_trips_layout_template) patch.intl_trips_layout_template = t.intl_trips_layout_template;
  if (t.intl_trip_card_template) patch.intl_trip_card_template = t.intl_trip_card_template;
  if (includeColors && t.palette) {
    patch.accent_color = t.palette.primary;
    patch.secondary_color = t.palette.secondary;
    patch.surface_color = t.palette.surface;
  }
  if (typeof t.show_fleet_section === 'boolean') patch.show_fleet_section = t.show_fleet_section;
  if (typeof t.show_why_us_section === 'boolean') patch.show_why_us_section = t.show_why_us_section;
  if (t.trips_section_eyebrow) patch.trips_section_eyebrow = t.trips_section_eyebrow;
  if (t.trips_section_title) patch.trips_section_title = t.trips_section_title;
  if (t.trips_section_subtitle) patch.trips_section_subtitle = t.trips_section_subtitle;
  return patch;
}

export function filterThemes({ category = 'all', query = '' }) {
  const q = query.trim().toLowerCase();
  return HOMEPAGE_THEMES.filter((t) => {
    if (category !== 'all' && t.category !== category) return false;
    if (!q) return true;
    const hay = [t.name, t.nameEl, t.description, t.mood, t.layoutLabel, ...(t.tags || [])]
      .join(' ')
      .toLowerCase();
    return hay.includes(q);
  });
}

export function themeCompositionLabel(theme) {
  return (
    theme.layoutLabel ||
    [theme.header_template, theme.hero_template, theme.trips_layout_template, theme.trip_card_template]
      .filter(Boolean)
      .join(' · ')
  );
}
