/** 20 πλήρη θέματα αρχικής — ίδιο schema πλατφόρμας, διαφορετική ταυτότητα το καθένα. */

export const THEME_CATEGORIES = [
  { id: 'all', label: 'Όλα', icon: 'apps' },
  { id: 'premium', label: 'Premium', icon: 'diamond' },
  { id: 'minimal', label: 'Minimal', icon: 'crop_free' },
  { id: 'bold', label: 'Έντονα', icon: 'bolt' },
  { id: 'corporate', label: 'Corporate', icon: 'business_center' },
  { id: 'seasonal', label: 'Εποχιακά', icon: 'sunny' },
];

/**
 * Κάθε θέμα = πλήρες custom πακέτο πάνω στα υποστηριζόμενα templates:
 * header × hero × trips layout × trip card × footer + palette + κείμενα.
 */
export const HOMEPAGE_THEMES = [
  {
    id: 'aegean_classic',
    name: 'Aegean Classic',
    nameEl: 'Κλασικό Αιγαίο',
    description: 'Το σήμα κατατεθέν ταξιδιωτικού γραφείου: glass header, fullscreen hero, premium κάρτες.',
    mood: 'Αιγαίο · αξιοπιστία',
    badge: 'Default',
    category: 'premium',
    tags: ['Glass', 'Fullscreen', 'Premium cards'],
    palette: { primary: '#0ea5e9', secondary: '#1e3a5f', hero: '#0f172a', surface: '#f8fafc' },
    header_template: 'glass_dark',
    hero_template: 'fullscreen_overlay',
    trips_layout_template: 'grid_three',
    trip_card_template: 'premium',
    footer_template: 'classic_columns',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'Ανακαλύψτε',
    trips_section_title: 'Εκδρομές στην Ελλάδα',
    trips_section_subtitle: 'Ημερήσιες και πολυήμερες διαδρομές με premium στόλο — κράτηση θέσης online.',
  },
  {
    id: 'mediterranean_sun',
    name: 'Mediterranean Sun',
    nameEl: 'Μεσογειακός Ήλιος',
    description: 'Ζεστό φως, teal & amber, split hero και μεγάλες cinematic κάρτες.',
    mood: 'Καλοκαίρι · ζεστασιά',
    badge: 'Warm',
    category: 'seasonal',
    tags: ['Split hero', 'Large cards', 'Contact footer'],
    palette: { primary: '#f59e0b', secondary: '#0f766e', hero: '#7c2d12', surface: '#fffbeb' },
    header_template: 'solid_light',
    hero_template: 'split_left',
    trips_layout_template: 'grid_two_large',
    trip_card_template: 'image_overlay',
    footer_template: 'split_contact',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'Ήλιος & θάλασσα',
    trips_section_title: 'Μεσογειακές αποδράσεις',
    trips_section_subtitle: 'Επιλεγμένες διαδρομές με άπλετο φως — ιδανικές για καλοκαιρινές κρατήσεις.',
  },
  {
    id: 'island_minimal',
    name: 'Island Minimal',
    nameEl: 'Νησιώτικο Minimal',
    description: 'Λευκός χώρος, λεπτή γραμμή, συμπαγής λίστα — boutique νησιωτικό look.',
    mood: 'Ήρεμο · καθαρό',
    badge: 'Boutique',
    category: 'minimal',
    tags: ['Minimal header', 'Compact list', 'Quiet'],
    palette: { primary: '#64748b', secondary: '#334155', hero: '#1e293b', surface: '#ffffff' },
    header_template: 'transparent_minimal',
    hero_template: 'centered_compact',
    trips_layout_template: 'compact_list',
    trip_card_template: 'minimal_clean',
    footer_template: 'minimal_center',
    show_fleet_section: false,
    show_why_us_section: true,
    trips_section_eyebrow: 'Επιλογές',
    trips_section_title: 'Επιλεγμένες διαδρομές',
    trips_section_subtitle: 'Λίγες, προσεγμένες εκδρομές — χωρίς θόρυβο, μόνο ουσία.',
  },
  {
    id: 'luxury_coach',
    name: 'Luxury Coach',
    nameEl: 'Luxury Coach',
    description: 'Navy & χρυσό, card-inset hero, magazine κάρτες και dark footer — VIP στόλος.',
    mood: 'VIP · χλιδή',
    badge: 'VIP',
    category: 'premium',
    tags: ['Card inset', 'Magazine', 'Dark footer'],
    palette: { primary: '#c9a227', secondary: '#0f172a', hero: '#020617', surface: '#f1f5f9' },
    header_template: 'bordered_elegant',
    hero_template: 'card_inset',
    trips_layout_template: 'masonry_two',
    trip_card_template: 'magazine',
    footer_template: 'dark_band',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'Private & VIP',
    trips_section_title: 'Luxury διαδρομές',
    trips_section_subtitle: 'Επιλεγμένα δρομολόγια με premium coach και προσωπική εξυπηρέτηση.',
  },
  {
    id: 'adventure_bold',
    name: 'Adventure Bold',
    nameEl: 'Περιπέτεια',
    description: 'Πορτοκαλί & βιολετί, gradient header, carousel και newsletter CTA.',
    mood: 'Ενέργεια · νεανικό',
    badge: 'Bold',
    category: 'bold',
    tags: ['Gradient', 'Carousel', 'Newsletter'],
    palette: { primary: '#ea580c', secondary: '#6d28d9', hero: '#431407', surface: '#fff7ed' },
    header_template: 'gradient_bar',
    hero_template: 'bottom_search',
    trips_layout_template: 'horizontal_scroll',
    trip_card_template: 'bordered_sharp',
    footer_template: 'newsletter_cta',
    show_fleet_section: true,
    show_why_us_section: false,
    trips_section_eyebrow: 'Next stop',
    trips_section_title: 'Περιπέτειες τώρα',
    trips_section_subtitle: 'Γρήγορες κρατήσεις, έντονες εμπειρίες — σύρετε για περισσότερα.',
  },
  {
    id: 'editorial_magazine',
    name: 'Editorial Magazine',
    nameEl: 'Editorial',
    description: 'Μονόχρωμο editorial, εναλλασσόμενες σειρές και storytelling κάρτες.',
    mood: 'Περιοδικό · story',
    badge: 'Editorial',
    category: 'premium',
    tags: ['Alternating', 'Magazine cards', 'Elegant'],
    palette: { primary: '#18181b', secondary: '#71717a', hero: '#09090b', surface: '#fafafa' },
    header_template: 'bordered_elegant',
    hero_template: 'split_left',
    trips_layout_template: 'alternating_rows',
    trip_card_template: 'magazine',
    footer_template: 'classic_columns',
    show_fleet_section: false,
    show_why_us_section: true,
    trips_section_eyebrow: 'Features',
    trips_section_title: 'Ιστορίες ταξιδιού',
    trips_section_subtitle: 'Κάθε εκδρομή σαν editorial feature — χώρος να «αναπνεύσει» η αφήγηση.',
  },
  {
    id: 'glass_modern',
    name: 'Glass Modern',
    nameEl: 'Glass Modern',
    description: 'Floating pill header, mesh hero, masonry & glass cards — ultra modern.',
    mood: 'Μελλοντικό · soft',
    badge: 'Modern',
    category: 'minimal',
    tags: ['Floating', 'Mesh', 'Glass'],
    palette: { primary: '#7c3aed', secondary: '#0891b2', hero: '#312e81', surface: '#f5f3ff' },
    header_template: 'floating_pill',
    hero_template: 'gradient_mesh',
    trips_layout_template: 'masonry_two',
    trip_card_template: 'glass_card',
    footer_template: 'minimal_center',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'Curated',
    trips_section_title: 'Σύγχρονες διαδρομές',
    trips_section_subtitle: 'Ελαφρύ UI, έντονα accents — ιδανικό για digital-first κοινό.',
  },
  {
    id: 'family_friendly',
    name: 'Family Friendly',
    nameEl: 'Οικογενειακό',
    description: 'Πράσινο & μπλε, φωτεινό, οριζόντιες κάρτες και footer επικοινωνίας.',
    mood: 'Οικογένεια · ασφάλεια',
    badge: 'Family',
    category: 'corporate',
    tags: ['Light header', 'Horizontal cards', 'Contact'],
    palette: { primary: '#16a34a', secondary: '#0369a1', hero: '#14532d', surface: '#f0fdf4' },
    header_template: 'solid_light',
    hero_template: 'fullscreen_overlay',
    trips_layout_template: 'grid_three',
    trip_card_template: 'compact_horizontal',
    footer_template: 'split_contact',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'Για όλους',
    trips_section_title: 'Οικογενειακές εκδρομές',
    trips_section_subtitle: 'Άνετες θέσεις, ξεκάθαρη πληροφόρηση — ιδανικό για οικογένειες.',
  },
  {
    id: 'europe_express',
    name: 'Europe Express',
    nameEl: 'Europe Express',
    description: 'Διεθνή δρομολόγια: floating header, μεγάλο hero, δύο μεγάλες κάρτες.',
    mood: 'Διεθνές · express',
    badge: 'EU',
    category: 'corporate',
    tags: ['Floating', 'Featured pair', 'Compact footer'],
    palette: { primary: '#2563eb', secondary: '#1e40af', hero: '#1e3a8a', surface: '#eff6ff' },
    header_template: 'floating_pill',
    hero_template: 'fullscreen_overlay',
    trips_layout_template: 'grid_two_large',
    trip_card_template: 'premium',
    footer_template: 'compact_inline',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'Cross-border',
    trips_section_title: 'Ευρωπαϊκά δρομολόγια',
    trips_section_subtitle: 'Αναχωρήσεις προς Ευρώπη με ξεκάθαρη τιμολόγηση και γρήγορη κράτηση.',
  },
  {
    id: 'summer_vibes',
    name: 'Summer Vibes',
    nameEl: 'Καλοκαιρινό',
    description: 'Coral & sky, gradient bar, carousel και cinematic overlays.',
    mood: 'Παραλία · fun',
    badge: 'Summer',
    category: 'seasonal',
    tags: ['Gradient', 'Scroll', 'Overlay'],
    palette: { primary: '#f43f5e', secondary: '#0ea5e9', hero: '#9f1239', surface: '#fff1f2' },
    header_template: 'gradient_bar',
    hero_template: 'split_left',
    trips_layout_template: 'horizontal_scroll',
    trip_card_template: 'image_overlay',
    footer_template: 'dark_band',
    show_fleet_section: true,
    show_why_us_section: false,
    trips_section_eyebrow: 'Hot list',
    trips_section_title: 'Καλοκαιρινά hits',
    trips_section_subtitle: 'Οι πιο ζεστές διαδρομές της σεζόν — σύρετε και κλείστε θέση.',
  },
  {
    id: 'corporate_travel',
    name: 'Corporate Travel',
    nameEl: 'Corporate',
    description: 'Ουδέτερα slate & teal, συμπαγής λίστα — για business κρατήσεις.',
    mood: 'Επαγγελματικό · γρήγορο',
    badge: 'B2B',
    category: 'corporate',
    tags: ['Solid', 'Compact list', 'Inline footer'],
    palette: { primary: '#0f766e', secondary: '#334155', hero: '#0f172a', surface: '#f8fafc' },
    header_template: 'solid_light',
    hero_template: 'centered_compact',
    trips_layout_template: 'compact_list',
    trip_card_template: 'minimal_clean',
    footer_template: 'compact_inline',
    show_fleet_section: false,
    show_why_us_section: false,
    trips_section_eyebrow: 'Schedule',
    trips_section_title: 'Επαγγελματικά δρομολόγια',
    trips_section_subtitle: 'Γρήγορη επισκόπηση διαδρομών — ιδανικό για επαναλαμβανόμενες κρατήσεις.',
  },
  {
    id: 'boutique_rose',
    name: 'Boutique Rose',
    nameEl: 'Boutique Rose',
    description: 'Ροζ accents, elegant border, card-inset και magazine layout.',
    mood: 'City break · soft luxury',
    badge: 'Rose',
    category: 'premium',
    tags: ['Elegant', 'Inset hero', 'Newsletter'],
    palette: { primary: '#e11d48', secondary: '#9f1239', hero: '#4c0519', surface: '#fff1f2' },
    header_template: 'bordered_elegant',
    hero_template: 'card_inset',
    trips_layout_template: 'grid_two_large',
    trip_card_template: 'magazine',
    footer_template: 'newsletter_cta',
    show_fleet_section: false,
    show_why_us_section: true,
    trips_section_eyebrow: 'City breaks',
    trips_section_title: 'Αποδράσεις πόλης',
    trips_section_subtitle: 'Στιγμιότυπα πολυτέλειας — για weekenders και romantic trips.',
  },
  {
    id: 'express_red',
    name: 'Express Red',
    nameEl: 'Express Coach',
    description: 'Κόκκινο brand strip, fullscreen hero, πυκνή λίστα — γρήγορες κρατήσεις.',
    mood: 'Ταχύτητα · ένταση',
    badge: 'Express',
    category: 'bold',
    tags: ['Gradient', 'Dense list', 'Speed'],
    palette: { primary: '#dc2626', secondary: '#111827', hero: '#450a0a', surface: '#fef2f2' },
    header_template: 'gradient_bar',
    hero_template: 'fullscreen_overlay',
    trips_layout_template: 'compact_list',
    trip_card_template: 'compact_horizontal',
    footer_template: 'compact_inline',
    show_fleet_section: true,
    show_why_us_section: false,
    trips_section_eyebrow: 'Departing soon',
    trips_section_title: 'Express αναχωρήσεις',
    trips_section_subtitle: 'Συμπαγής λίστα για γρήγορη επιλογή και άμεση κράτηση.',
  },
  {
    id: 'greek_heritage',
    name: 'Greek Heritage',
    nameEl: 'Ελληνική Κληρονομιά',
    description: 'Terracotta & navy, storytelling rows — πολιτιστικές περιηγήσεις.',
    mood: 'Πολιτισμός · παράδοση',
    badge: 'Heritage',
    category: 'premium',
    tags: ['Glass', 'Story rows', 'Classic footer'],
    palette: { primary: '#c2410c', secondary: '#1e3a5f', hero: '#431407', surface: '#fff7ed' },
    header_template: 'glass_dark',
    hero_template: 'split_left',
    trips_layout_template: 'alternating_rows',
    trip_card_template: 'premium',
    footer_template: 'classic_columns',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'Heritage',
    trips_section_title: 'Πολιτιστικές διαδρομές',
    trips_section_subtitle: 'Μνημεία, ιστορία και τοπική γεύση — αφήγηση σε κάθε στάση.',
  },
  {
    id: 'night_luxe',
    name: 'Night Luxe',
    nameEl: 'Night Luxe',
    description: 'Σκούρο cinematic theme: violet & gold, overlay κάρτες, dark band.',
    mood: 'Νύχτα · luxe',
    badge: 'Night',
    category: 'premium',
    tags: ['Dark surface', 'Overlay', 'Cinematic'],
    palette: { primary: '#a78bfa', secondary: '#fbbf24', hero: '#0c0a09', surface: '#1c1917' },
    header_template: 'glass_dark',
    hero_template: 'fullscreen_overlay',
    trips_layout_template: 'grid_two_large',
    trip_card_template: 'image_overlay',
    footer_template: 'dark_band',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'After dark',
    trips_section_title: 'Night experiences',
    trips_section_subtitle: 'Σκούρο UI με χρυσές λεπτομέρειες — για premium νυχτερινές εμπειρίες.',
  },
  {
    id: 'conversion_pro',
    name: 'Conversion Pro',
    nameEl: 'Conversion Pro',
    description: 'Βελτιστοποιημένο για κρατήσεις: search στο hero, 3στήλο grid, newsletter.',
    mood: 'Conversion · ROI',
    badge: 'Convert',
    category: 'corporate',
    tags: ['Search hero', '3-col', 'Newsletter'],
    palette: { primary: '#0284c7', secondary: '#0c4a6e', hero: '#082f49', surface: '#f0f9ff' },
    header_template: 'floating_pill',
    hero_template: 'bottom_search',
    trips_layout_template: 'grid_three',
    trip_card_template: 'premium',
    footer_template: 'newsletter_cta',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'Book now',
    trips_section_title: 'Διαθέσιμες εκδρομές',
    trips_section_subtitle: 'Καθαρή ιεραρχία και CTA σε κάθε κάρτα — σχεδιασμένο για μετατροπές.',
  },
  {
    id: 'wanderlust_green',
    name: 'Wanderlust',
    nameEl: 'Wanderlust',
    description: 'Emerald φύση, mesh hero, masonry και glass cards.',
    mood: 'Φύση · explore',
    badge: 'Nature',
    category: 'seasonal',
    tags: ['Mesh', 'Masonry', 'Glass'],
    palette: { primary: '#059669', secondary: '#047857', hero: '#022c22', surface: '#ecfdf5' },
    header_template: 'transparent_minimal',
    hero_template: 'gradient_mesh',
    trips_layout_template: 'masonry_two',
    trip_card_template: 'glass_card',
    footer_template: 'split_contact',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'Explore',
    trips_section_title: 'Φύση & διαδρομές',
    trips_section_subtitle: 'Πράσινα accents και ανάλαφρες κάρτες — για outdoor & eco trips.',
  },
  {
    id: 'fresh_startup',
    name: 'Fresh Startup',
    nameEl: 'Φρέσκο',
    description: 'Mint & white, card-inset hero, horizontal scroll — startup energy.',
    mood: 'Νεανικό · fresh',
    badge: 'Fresh',
    category: 'minimal',
    tags: ['Inset', 'Scroll', 'Glass'],
    palette: { primary: '#14b8a6', secondary: '#0f766e', hero: '#134e4a', surface: '#f0fdfa' },
    header_template: 'solid_light',
    hero_template: 'card_inset',
    trips_layout_template: 'horizontal_scroll',
    trip_card_template: 'glass_card',
    footer_template: 'minimal_center',
    show_fleet_section: false,
    show_why_us_section: true,
    trips_section_eyebrow: 'New drops',
    trips_section_title: 'Φρέσκες διαδρομές',
    trips_section_subtitle: 'Ελαφρύ, μοντέρνο UI — ιδανικό για νέα brands και νεανικό κοινό.',
  },
  {
    id: 'heritage_classic',
    name: 'Heritage Classic',
    nameEl: 'Παραδοσιακό',
    description: 'Burgundy & cream, elegant border, sharp cards — κλασικό ελληνικό γραφείο.',
    mood: 'Παράδοση · κύρος',
    badge: 'Classic',
    category: 'corporate',
    tags: ['Elegant', 'Sharp cards', 'Columns'],
    palette: { primary: '#7f1d1d', secondary: '#b45309', hero: '#450a0a', surface: '#fefce8' },
    header_template: 'bordered_elegant',
    hero_template: 'fullscreen_overlay',
    trips_layout_template: 'grid_three',
    trip_card_template: 'bordered_sharp',
    footer_template: 'classic_columns',
    show_fleet_section: true,
    show_why_us_section: true,
    trips_section_eyebrow: 'Παράδοση',
    trips_section_title: 'Κλασικές διαδρομές',
    trips_section_subtitle: 'Έντονο brand, καθαρές γραμμές — για γραφεία με ιστορία.',
  },
  {
    id: 'ultra_clean',
    name: 'Ultra Clean',
    nameEl: 'Ultra Clean',
    description: 'Monochrome minimal: μόνο τα απαραίτητα, κεντραρισμένο hero, 3στήλο clean grid.',
    mood: 'Zero noise · focus',
    badge: 'Clean',
    category: 'minimal',
    tags: ['Minimal', 'Clean cards', 'Center hero'],
    palette: { primary: '#171717', secondary: '#525252', hero: '#0a0a0a', surface: '#ffffff' },
    header_template: 'transparent_minimal',
    hero_template: 'centered_compact',
    trips_layout_template: 'grid_three',
    trip_card_template: 'minimal_clean',
    footer_template: 'minimal_center',
    show_fleet_section: false,
    show_why_us_section: false,
    trips_section_eyebrow: 'Trips',
    trips_section_title: 'Διαδρομές',
    trips_section_subtitle: 'Μόνο τίτλος, ημερομηνία και τιμή — χωρίς διακοσμητικό θόρυβο.',
  },
];

export const DEFAULT_HOMEPAGE_THEME_ID = 'aegean_classic';

export function getHomepageThemeById(id) {
  return HOMEPAGE_THEMES.find((t) => t.id === id) || HOMEPAGE_THEMES[0];
}

/** Μετατρέπει θέμα σε πλήρες patch για site appearance API. */
export function themeToAppearancePatch(theme) {
  const t = theme || getHomepageThemeById(DEFAULT_HOMEPAGE_THEME_ID);
  const patch = {
    homepage_theme_id: t.id,
    accent_color: t.palette.primary,
    secondary_color: t.palette.secondary,
    surface_color: t.palette.surface,
    header_template: t.header_template,
    hero_template: t.hero_template,
    trips_layout_template: t.trips_layout_template,
    trip_card_template: t.trip_card_template,
    footer_template: t.footer_template,
  };
  if (typeof t.show_fleet_section === 'boolean') patch.show_fleet_section = t.show_fleet_section;
  if (typeof t.show_why_us_section === 'boolean') patch.show_why_us_section = t.show_why_us_section;
  if (t.trips_section_eyebrow) patch.trips_section_eyebrow = t.trips_section_eyebrow;
  if (t.trips_section_title) patch.trips_section_title = t.trips_section_title;
  if (t.trips_section_subtitle) patch.trips_section_subtitle = t.trips_section_subtitle;
  return patch;
}

export function filterThemes({ category = 'all', query = '' }) {
  const q = query.trim().toLowerCase();
  return HOMEPAGE_THEMES.filter((t) => {
    if (category !== 'all' && t.category !== category) return false;
    if (!q) return true;
    const hay = [t.name, t.nameEl, t.description, t.mood, ...(t.tags || [])].join(' ').toLowerCase();
    return hay.includes(q);
  });
}

/** Helper: σύνθεση templates για UI chips. */
export function themeCompositionLabel(theme) {
  return [
    theme.header_template,
    theme.hero_template,
    theme.trips_layout_template,
    theme.trip_card_template,
    theme.footer_template,
  ].join(' · ');
}
