/** 20 πλήρη θέματα αρχικής σελίδας — συνδυασμός layout + χρωμάτων. */

export const THEME_CATEGORIES = [
  { id: 'all', label: 'Όλα' },
  { id: 'premium', label: 'Premium' },
  { id: 'minimal', label: 'Minimal' },
  { id: 'bold', label: 'Έντονα' },
  { id: 'corporate', label: 'Corporate' },
  { id: 'seasonal', label: 'Εποχιακά' },
];

const T = (theme) => theme;

export const HOMEPAGE_THEMES = [
  T({
    id: 'aegean_classic',
    name: 'Aegean Classic',
    nameEl: 'Κλασικό Αιγαίο',
    description: 'Σκούρο glass header, fullscreen hero, premium κάρτες — το default για ταξιδιωτικά γραφεία.',
    category: 'premium',
    palette: { primary: '#0ea5e9', secondary: '#1e3a5f', hero: '#0f172a', surface: '#f8fafc' },
    header_template: 'glass_dark',
    hero_template: 'fullscreen_overlay',
    trips_layout_template: 'grid_three',
    trip_card_template: 'premium',
    footer_template: 'classic_columns',
  }),
  T({
    id: 'mediterranean_sun',
    name: 'Mediterranean Sun',
    nameEl: 'Μεσογειακός Ήλιος',
    description: 'Φωτεινό, ζεστό palette με split hero και μεγάλες κάρτες εκδρομών.',
    category: 'seasonal',
    palette: { primary: '#f59e0b', secondary: '#0d9488', hero: '#78350f', surface: '#fffbeb' },
    header_template: 'solid_light',
    hero_template: 'split_left',
    trips_layout_template: 'grid_two_large',
    trip_card_template: 'image_overlay',
    footer_template: 'split_contact',
  }),
  T({
    id: 'island_minimal',
    name: 'Island Minimal',
    nameEl: 'Νησιώτικο Minimal',
    description: 'Καθαρές γραμμές, συμπαγής λίστα, λευκός χώρος — για boutique agencies.',
    category: 'minimal',
    palette: { primary: '#64748b', secondary: '#94a3b8', hero: '#334155', surface: '#ffffff' },
    header_template: 'transparent_minimal',
    hero_template: 'centered_compact',
    trips_layout_template: 'compact_list',
    trip_card_template: 'minimal_clean',
    footer_template: 'minimal_center',
  }),
  T({
    id: 'luxury_coach',
    name: 'Luxury Coach',
    nameEl: 'Luxury Coach',
    description: 'Navy & gold αίσθηση, card-inset hero, dark footer — VIP στόλος.',
    category: 'premium',
    palette: { primary: '#c9a227', secondary: '#0f172a', hero: '#020617', surface: '#f1f5f9' },
    header_template: 'glass_dark',
    hero_template: 'card_inset',
    trips_layout_template: 'grid_two_large',
    trip_card_template: 'premium',
    footer_template: 'dark_band',
  }),
  T({
    id: 'adventure_bold',
    name: 'Adventure Bold',
    nameEl: 'Περιπέτεια',
    description: 'Έντονα χρώματα, carousel εκδρομών, newsletter footer — για νεανικό κοινό.',
    category: 'bold',
    palette: { primary: '#ea580c', secondary: '#7c3aed', hero: '#431407', surface: '#fff7ed' },
    header_template: 'gradient_bar',
    hero_template: 'bottom_search',
    trips_layout_template: 'horizontal_scroll',
    trip_card_template: 'bordered_sharp',
    footer_template: 'newsletter_cta',
  }),
  T({
    id: 'editorial_magazine',
    name: 'Editorial Magazine',
    nameEl: 'Editorial',
    description: 'Magazine κάρτες, εναλλασσόμενες σειρές — storytelling ταξίδια.',
    category: 'premium',
    palette: { primary: '#18181b', secondary: '#71717a', hero: '#09090b', surface: '#fafafa' },
    header_template: 'bordered_elegant',
    hero_template: 'split_left',
    trips_layout_template: 'alternating_rows',
    trip_card_template: 'magazine',
    footer_template: 'classic_columns',
  }),
  T({
    id: 'glass_modern',
    name: 'Glass Modern',
    nameEl: 'Glass Modern',
    description: 'Floating header, gradient mesh hero, glass cards — Apple-style.',
    category: 'minimal',
    palette: { primary: '#8b5cf6', secondary: '#06b6d4', hero: '#4c1d95', surface: '#f5f3ff' },
    header_template: 'floating_pill',
    hero_template: 'gradient_mesh',
    trips_layout_template: 'masonry_two',
    trip_card_template: 'glass_card',
    footer_template: 'minimal_center',
  }),
  T({
    id: 'family_friendly',
    name: 'Family Friendly',
    nameEl: 'Οικογενειακό',
    description: 'Φιλικό, φωτεινό UI με grid 3 στήλες και επικοινωνία στο footer.',
    category: 'corporate',
    palette: { primary: '#16a34a', secondary: '#0284c7', hero: '#14532d', surface: '#f0fdf4' },
    header_template: 'solid_light',
    hero_template: 'fullscreen_overlay',
    trips_layout_template: 'grid_three',
    trip_card_template: 'compact_horizontal',
    footer_template: 'split_contact',
  }),
  T({
    id: 'europe_express',
    name: 'Europe Express',
    nameEl: 'Europe Express',
    description: 'Διεθνή δρομολόγια — premium look με κλασικό layout.',
    category: 'corporate',
    palette: { primary: '#2563eb', secondary: '#1d4ed8', hero: '#1e3a8a', surface: '#eff6ff' },
    header_template: 'glass_dark',
    hero_template: 'fullscreen_overlay',
    trips_layout_template: 'grid_three',
    trip_card_template: 'premium',
    footer_template: 'classic_columns',
  }),
  T({
    id: 'summer_vibes',
    name: 'Summer Vibes',
    nameEl: 'Καλοκαιρινό',
    description: 'Coral & sky, horizontal scroll, cinematic κάρτες.',
    category: 'seasonal',
    palette: { primary: '#f43f5e', secondary: '#38bdf8', hero: '#881337', surface: '#fff1f2' },
    header_template: 'gradient_bar',
    hero_template: 'bottom_search',
    trips_layout_template: 'horizontal_scroll',
    trip_card_template: 'image_overlay',
    footer_template: 'dark_band',
  }),
  T({
    id: 'corporate_travel',
    name: 'Corporate Travel',
    nameEl: 'Corporate',
    description: 'Επαγγελματικό, συμπαγές, γρήγορη πρόσβαση σε εκδρομές.',
    category: 'corporate',
    palette: { primary: '#475569', secondary: '#0f766e', hero: '#1e293b', surface: '#f8fafc' },
    header_template: 'solid_light',
    hero_template: 'centered_compact',
    trips_layout_template: 'grid_three',
    trip_card_template: 'minimal_clean',
    footer_template: 'compact_inline',
  }),
  T({
    id: 'boutique_rose',
    name: 'Boutique Rose',
    nameEl: 'Boutique Rose',
    description: 'Ροζ accents, magazine layout — για luxury city breaks.',
    category: 'premium',
    palette: { primary: '#e11d48', secondary: '#fda4af', hero: '#4c0519', surface: '#fff1f2' },
    header_template: 'bordered_elegant',
    hero_template: 'card_inset',
    trips_layout_template: 'grid_two_large',
    trip_card_template: 'magazine',
    footer_template: 'minimal_center',
  }),
  T({
    id: 'express_red',
    name: 'Express Red',
    nameEl: 'Express Coach',
    description: 'Κόκκινο brand strip, compact λίστα — γρήγορες κρατήσεις.',
    category: 'bold',
    palette: { primary: '#dc2626', secondary: '#1f2937', hero: '#450a0a', surface: '#fef2f2' },
    header_template: 'gradient_bar',
    hero_template: 'fullscreen_overlay',
    trips_layout_template: 'compact_list',
    trip_card_template: 'compact_horizontal',
    footer_template: 'compact_inline',
  }),
  T({
    id: 'greek_heritage',
    name: 'Greek Heritage',
    nameEl: 'Ελληνική Κληρονομιά',
    description: 'Terracotta & navy, storytelling rows — cultural tours.',
    category: 'premium',
    palette: { primary: '#c2410c', secondary: '#1e3a5f', hero: '#431407', surface: '#fff7ed' },
    header_template: 'glass_dark',
    hero_template: 'split_left',
    trips_layout_template: 'alternating_rows',
    trip_card_template: 'premium',
    footer_template: 'classic_columns',
  }),
  T({
    id: 'night_luxe',
    name: 'Night Luxe',
    nameEl: 'Night Luxe',
    description: 'Σκούρο cinematic theme με overlay κάρτες.',
    category: 'premium',
    palette: { primary: '#a78bfa', secondary: '#fbbf24', hero: '#0c0a09', surface: '#1c1917' },
    header_template: 'glass_dark',
    hero_template: 'fullscreen_overlay',
    trips_layout_template: 'grid_two_large',
    trip_card_template: 'image_overlay',
    footer_template: 'dark_band',
  }),
  T({
    id: 'conversion_pro',
    name: 'Conversion Pro',
    nameEl: 'Conversion Pro',
    description: 'Βελτιστοποιημένο για κρατήσεις — search στο hero, newsletter.',
    category: 'corporate',
    palette: { primary: '#0284c7', secondary: '#0369a1', hero: '#0c4a6e', surface: '#f0f9ff' },
    header_template: 'floating_pill',
    hero_template: 'bottom_search',
    trips_layout_template: 'grid_three',
    trip_card_template: 'premium',
    footer_template: 'newsletter_cta',
  }),
  T({
    id: 'wanderlust_green',
    name: 'Wanderlust',
    nameEl: 'Wanderlust',
    description: 'Emerald φύση, masonry grid, glass cards.',
    category: 'seasonal',
    palette: { primary: '#059669', secondary: '#34d399', hero: '#064e3b', surface: '#ecfdf5' },
    header_template: 'transparent_minimal',
    hero_template: 'gradient_mesh',
    trips_layout_template: 'masonry_two',
    trip_card_template: 'glass_card',
    footer_template: 'split_contact',
  }),
  T({
    id: 'fresh_startup',
    name: 'Fresh Startup',
    nameEl: 'Φρέσκο',
    description: 'Mint & white, horizontal scroll — νεανικό startup look.',
    category: 'minimal',
    palette: { primary: '#14b8a6', secondary: '#5eead4', hero: '#134e4a', surface: '#f0fdfa' },
    header_template: 'solid_light',
    hero_template: 'card_inset',
    trips_layout_template: 'horizontal_scroll',
    trip_card_template: 'glass_card',
    footer_template: 'minimal_center',
  }),
  T({
    id: 'heritage_classic',
    name: 'Heritage Classic',
    nameEl: 'Παραδοσιακό',
    description: 'Burgundy & cream — κλασικό ελληνικό γραφείο.',
    category: 'corporate',
    palette: { primary: '#7f1d1d', secondary: '#b45309', hero: '#450a0a', surface: '#fefce8' },
    header_template: 'bordered_elegant',
    hero_template: 'fullscreen_overlay',
    trips_layout_template: 'grid_three',
    trip_card_template: 'bordered_sharp',
    footer_template: 'classic_columns',
  }),
  T({
    id: 'ultra_clean',
    name: 'Ultra Clean',
    nameEl: 'Ultra Clean',
    description: 'Μόνο τα απαραίτητα — monochrome minimal.',
    category: 'minimal',
    palette: { primary: '#171717', secondary: '#737373', hero: '#0a0a0a', surface: '#ffffff' },
    header_template: 'transparent_minimal',
    hero_template: 'centered_compact',
    trips_layout_template: 'compact_list',
    trip_card_template: 'minimal_clean',
    footer_template: 'compact_inline',
  }),
];

export const DEFAULT_HOMEPAGE_THEME_ID = 'aegean_classic';

export function getHomepageThemeById(id) {
  return HOMEPAGE_THEMES.find((t) => t.id === id) || HOMEPAGE_THEMES[0];
}

/** Μετατρέπει θέμα σε patch για site appearance API. */
export function themeToAppearancePatch(theme) {
  return {
    homepage_theme_id: theme.id,
    accent_color: theme.palette.primary,
    secondary_color: theme.palette.secondary,
    surface_color: theme.palette.surface,
    header_template: theme.header_template,
    hero_template: theme.hero_template,
    trips_layout_template: theme.trips_layout_template,
    trip_card_template: theme.trip_card_template,
    footer_template: theme.footer_template,
  };
}

export function filterThemes({ category = 'all', query = '' }) {
  const q = query.trim().toLowerCase();
  return HOMEPAGE_THEMES.filter((t) => {
    if (category !== 'all' && t.category !== category) return false;
    if (!q) return true;
    return (
      t.name.toLowerCase().includes(q) ||
      t.nameEl.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q)
    );
  });
}
